name: fragvest_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# IOS version
version: 6.0.2+50
# Android version
# version: 1.0.0+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.29
  google_fonts: ^2.1.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  # persistent_bottom_nav_bar: ^4.0.2
  persistent_bottom_nav_bar_v2: ^4.2.5
  provider: ^6.0.1
  curved_nav_bar: ^0.0.2
  pie_chart: ^5.1.0
  modal_bottom_sheet: ^2.0.0
  readmore: ^2.1.0
  flutter_rating_bar: ^4.0.0
  speech_bubble: ^0.0.9
  image_picker: ^0.8.4
  searchfield: ^0.5.6
  flutter_credit_card: ^3.0.1
  http: ^0.13.3
  logger: ^1.1.0
  select_form_field: ^2.2.0
  # cached_network_image: ^3.1.0
  cached_network_image: ^3.2.1
  pin_code_fields: ^7.3.0
  awesome_dialog: ^2.1.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  http_parser: ^4.0.0
  # flutter_paystack: ^1.0.5+1
  # flutter_paystack_client: ^0.1.1
  basic_utils: ^4.0.0
  flutter_easyloading: ^3.0.3
  syncfusion_flutter_datepicker: ^19.4.47
  flutter_date_pickers: ^0.2.8
  flutter_clean_calendar: ^1.1.0
  table_calendar: ^3.0.3
  google_maps_flutter: ^2.2.1
  pattern_formatter: ^2.0.0
  url_launcher: ^6.0.18
  flutter_phone_direct_caller: ^2.1.0
  emoji_picker_flutter: ^1.3.0
  shared_preferences: ^2.0.13
  webview_flutter: ^3.0.0
  # flutterwave: ^1.0.1
  flutterwave_standard: ^1.0.3
  # paystack_manager: ^1.0.4
  # flutter_paystack_payment:
  get_it: ^7.2.0
  equatable: ^2.0.3
  jiffy: ^5.0.0
#  camera: ^0.9.4+18
#  path_provider: ^2.0.9
#  path: ^1.8.0
  flutter_pin_code_fields: ^1.1.0
  pinput: ^2.2.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.0.3
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#0C0932"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo3.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "dev_assets/logo3.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
